apiVersion: v1
kind: Pod
metadata:
  name: helloworld-app
  labels:
    app: helloworld
spec:
  containers:
  - name: helloworld-api
    image: profilingwidgetacr.azurecr.io/helloworld:latest
    ports:
    - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-app-service
spec:
  type: LoadBalancer
  selector:
    app: helloworld
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081